name: Wf-4
on: workflow_dispatch
env:
  app_name: testapp
  version: v1.1
  owner: hsbc
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      app_name: mbapp
      os_name: Windows
    steps:
    - name: step-1
      run: |
        echo "App Name is $app_name"
        echo "App version is ${{ env.version }}"
        echo "App Supported Os is ${{ env.os_name }}"        
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: job2step1
      run: |
         echo "App Name & version is ${{ env.app_name }} ${{ env.version }}"
         echo "App Supported Os is ${{ env.os_name }}"          
  