name: Wf-5 Secrets
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "DB Passwd is ${{ secrets.DB_PASSWD }}"
        echo "${{ github.ref }}
