name: WF-1
on: 
  workflow_dispatch: 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Msg
      run: |
        echo "Hello World"
        echo "Todays date is $(date)"        
      
      
      
     
      
  